In [109]:
import pandas as pd

In [110]:
products = pd.read_csv('olist_products_dataset.csv')

In [111]:
products

,product_id,product_category_name,product_name_english,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,Professional Essential Oil Diffuser,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,Compact Sketchbook,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,Comfort Yoga Mat,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,Everyday Baby Monitor,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,Deluxe Kitchen Scale,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,Modern Picture Frame,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,Professional Flashlight,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,Everyday Cotton Bed Sheet Set,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,Modern Webcam,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,Essential Duvet Cover,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [98]:
def category_translation(category_name):
    category = {
'beleza_saude': 'health_beauty',
'informatica_acessorios': 'computers_accessories',
'automotivo': 'auto',
'cama_mesa_banho': 'bed_bath_table',
'moveis_decoracao': 'furniture_decor',
'esporte_lazer': 'sports_leisure',
'perfumaria': 'perfumery',
'utilidades_domesticas': 'housewares',
'telefonia': 'telephony',
'relogios_presentes': 'watches_gifts',
'alimentos_bebidas': 'food_drink',
'bebes': 'baby',
'papelaria': 'stationery',
'tablets_impressao_imagem': 'tablets_printing_image',
'brinquedos': 'toys',
'telefonia_fixa': 'fixed_telephony',
'ferramentas_jardim': 'garden_tools',
'fashion_bolsas_e_acessorios': 'fashion_bags_accessories',
'eletroportateis': 'small_appliances',
'consoles_games': 'consoles_games',
'audio': 'audio',
'fashion_calcados': 'fashion_shoes',
'cool_stuff': 'cool_stuff',
'malas_acessorios': 'luggage_accessories',
'climatizacao': 'air_conditioning',
'construcao_ferramentas_construcao': 'construction_tools_construction',
'moveis_cozinha_area_de_servico_jantar_e_jardim': 'kitchen_dining_laundry_garden_furniture',
'construcao_ferramentas_jardim': 'construction_tools_garden',
'fashion_roupa_masculina': 'fashion_male_clothing',
'pet_shop': 'pet_shop',
'moveis_escritorio': 'office_furniture',
'market_place': 'market_place',
'eletronicos': 'electronics',
'eletrodomesticos': 'home_appliances',
'artigos_de_festas': 'party_supplies',
'casa_conforto': 'home_confort',
'construcao_ferramentas_ferramentas': 'construction_tools_tools',
'agro_industria_e_comercio': 'agro_industry_and_commerce',
'moveis_colchao_e_estofado': 'furniture_mattress_and_upholstery',
'livros_tecnicos': 'books_technical',
'casa_construcao': 'home_construction',
'instrumentos_musicais': 'musical_instruments',
'moveis_sala': 'furniture_living_room',
'construcao_ferramentas_iluminacao': 'construction_tools_lights',
'industria_comercio_e_negocios': 'industry_commerce_and_business',
'alimentos': 'food',
'artes': 'art',
'moveis_quarto': 'furniture_bedroom',
'livros_interesse_geral': 'books_general_interest',
'construcao_ferramentas_seguranca': 'construction_tools_safety',
'fashion_underwear_e_moda_praia': 'fashion_underwear_beach',
'fashion_esporte': 'fashion_sport',
'sinalizacao_e_seguranca': 'signaling_and_security',
'pcs': 'computers',
'artigos_de_natal': 'christmas_supplies',
'fashion_roupa_feminina': 'fashion_female_clothing',
'eletrodomesticos_2': 'home_appliances_2',
'livros_importados': 'books_imported',
'bebidas': 'drinks',
'cine_foto': 'cine_photo',
'la_cuisine': 'la_cuisine',
'musica': 'music',
'casa_conforto_2': 'home_comfort_2',
'portateis_casa_forno_e_cafe': 'small_appliances_home_oven_and_coffee',
'cds_dvds_musicais': 'cds_dvds_musicals',
'dvds_blu_ray': 'dvds_blu_ray',
'flores': 'flowers',
'artes_e_artesanato': 'arts_and_craftmanship',
'fraldas_higiene': 'diapers_and_hygiene',
'fashion_roupa_infanto_juvenil': 'fashion_childrens_clothes',
'seguros_e_servicos': 'security_and_services'
}
    if category_name in category:
        return category[category_name]
    return category_name

In [112]:
products['product_category_name'] = products['product_category_name'].apply(category_translation)

In [113]:
products

,product_id,product_category_name,product_name_english,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,Professional Essential Oil Diffuser,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,art,Compact Sketchbook,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,sports_leisure,Comfort Yoga Mat,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,baby,Everyday Baby Monitor,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,housewares,Deluxe Kitchen Scale,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,furniture_decor,Modern Picture Frame,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construction_tools_lights,Professional Flashlight,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,bed_bath_table,Everyday Cotton Bed Sheet Set,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,computers_accessories,Modern Webcam,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,bed_bath_table,Essential Duvet Cover,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [114]:
# check nulls
products.isna().sum()

product_id                      0
product_category_name         610
product_name_english            0
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [115]:
products.shape

(32951, 10)

In [116]:
products.drop_duplicates(inplace=True , keep='first')

In [117]:
products.dropna(inplace=True)

In [118]:
products.shape

(32340, 10)

In [119]:
products.dtypes

product_id                        str
product_category_name             str
product_name_english              str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [120]:
pd.DataFrame.to_csv(products, 'olist_products_dataset.csv',index=False)