In [59]:
import pandas as pd

In [60]:
reviews = pd.read_csv('olist_order_reviews_dataset.csv',index_col=0)

In [61]:
reviews

,order_id,review_score,review_comment_message,review_creation_date,review_answer_timestamp,review_class
review_id,,,,,,
7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,No Comment,1/18/2018 0:00,1/18/2018 21:46,No Comment
80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,No Comment,3/10/2018 0:00,3/11/2018 3:05,No Comment
228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,No Comment,2/17/2018 0:00,2/18/2018 14:36,No Comment
e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,I received it well before the estimated date.,4/21/2017 0:00,4/21/2017 22:02,Delivery
f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,"Congratulations Lannister stores, I loved shop...",3/1/2018 0:00,3/2/2018 10:26,Customer Service
...,...,...,...,...,...,...
574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,No Comment,7/7/2018 0:00,7/14/2018 17:18,No Comment
f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,No Comment,12/9/2017 0:00,12/11/2017 20:06,No Comment
b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,"Excellent backpack, super fast delivery. I hig...",3/22/2018 0:00,3/23/2018 9:10,Customer Service
1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,No Comment,7/1/2018 0:00,7/2/2018 12:59,No Comment
efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,My product arrived and I already have to retur...,7/3/2017 0:00,7/3/2017 21:01,Customer Service

In [62]:
# check duplicates
reviews.duplicated().sum()

np.int64(23)

In [63]:
# check nulls
reviews.isna().sum()

order_id                   0
review_score               0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
review_class               0
dtype: int64

In [64]:
reviews.shape

(99224, 6)

In [65]:
reviews['review_comment_message'] = reviews['review_comment_message'].fillna('No Comment')

In [66]:
reviews

,order_id,review_score,review_comment_message,review_creation_date,review_answer_timestamp,review_class
review_id,,,,,,
7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,No Comment,1/18/2018 0:00,1/18/2018 21:46,No Comment
80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,No Comment,3/10/2018 0:00,3/11/2018 3:05,No Comment
228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,No Comment,2/17/2018 0:00,2/18/2018 14:36,No Comment
e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,I received it well before the estimated date.,4/21/2017 0:00,4/21/2017 22:02,Delivery
f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,"Congratulations Lannister stores, I loved shop...",3/1/2018 0:00,3/2/2018 10:26,Customer Service
...,...,...,...,...,...,...
574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,No Comment,7/7/2018 0:00,7/14/2018 17:18,No Comment
f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,No Comment,12/9/2017 0:00,12/11/2017 20:06,No Comment
b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,"Excellent backpack, super fast delivery. I hig...",3/22/2018 0:00,3/23/2018 9:10,Customer Service
1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,No Comment,7/1/2018 0:00,7/2/2018 12:59,No Comment
efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,My product arrived and I already have to retur...,7/3/2017 0:00,7/3/2017 21:01,Customer Service

In [67]:
def classify_review(text):
    if not isinstance(text, str) or text.strip().lower() == "no comment" or text.strip() == "":
        return "No Comment"

    text = text.lower()

    if any(word in text for word in [
        "box", "bag", "inside", "packaging", "sealed", "wrapped",
        "bubble", "wrap", "seal", "crushed", "packaged", "came",
        "bubble wrap", "without packaging", "broken box", "crushed box"
    ]):
        return "Packaging"

    elif any(word in text for word in [
        "money", "price", "worth", "value", "cost", "expensive",
        "paid", "buying", "overpriced", "cheap", "affordable",
        "waste of money", "not worth", "good price", "great value"
    ]):
        return "Price"

    elif any(word in text for word in [
        "service", "response", "exchange", "refund", "seller",
        "return", "contact", "waiting", "sent", "lannister",
        "customer", "store", "shop", "support", "ignored",
        "no reply", "no response", "unresolved", "resolved"
    ]):
        return "Customer Service"

    elif any(word in text for word in [
        "arrived", "delivery", "schedule", "ahead", "deadline",
        "delivered", "shipping", "date", "days", "dispatch",
        "fast delivery", "quick delivery", "late", "delayed",
        "not delivered", "still waiting", "never received",
        "tracking", "transit", "courier", "on time", "early"
    ]):
        return "Delivery"

    elif any(word in text for word in [
        "quality", "excellent", "good", "great", "loved",
        "beautiful", "expected", "liked", "perfect", "product",
        "works", "durable", "defective", "broken", "damaged",
        "fake", "original", "inferior", "poor quality", "well made",
        "not as described", "exactly as described", "sturdy", "flimsy"
    ]):
        return "Product Quality"

    return "Other"

In [68]:
reviews['review_class'] = reviews['review_comment_message'].apply(classify_review)
reviews['review_class']

review_id
7bc2406110b926393aa56f80a40eba40          No Comment
80e641a11e56f04c1ad469d5645fdfde          No Comment
228ce5500dc1d8e020d8d1322874b6f0          No Comment
e64fb393e7b32834bb789ff8bb30750e            Delivery
f7c4243c7fe1938f181bec41a392bdeb    Customer Service
                                          ...
574ed12dd733e5fa530cfd4bbf39d7c9          No Comment
f3897127253a9592a73be9bdfdf4ed7a          No Comment
b3de70c89b1510c4cd3d0649fd302472    Customer Service
1adeb9d84d72fe4e337617733eb85149          No Comment
efe49f1d6f951dd88b51e6ccd4cc548f    Customer Service
Name: review_class, Length: 99224, dtype: str

In [69]:
# check comments of bad score reviews
reviews[['review_comment_message','review_class', 'review_score']][(reviews['review_score'] == 1) & (reviews['review_comment_message'] != 'No Comment')]

,review_comment_message,review_class,review_score
review_id,,,
373cbeecea8286a2b66c97b1b157ec46,Terrible,Other,1
2c5e27fc178bde7ac173c9c62c31b070,I didn't like it! I bought a pig in a poke.,Other,1
58044bca115705a48fe0e00a21390c54,always buy online and the delivery arrives bef...,Delivery,1
9fd59cd04b42f600df9f25e54082a8d1,My order still hasn't arrived.,Delivery,1
e233e51d11511bf30e568c76360ace52,I only received 1 Midea Split ESTILO remote co...,Other,1
...,...,...,...
9bab7509047d0b236205e330172b384d,would like to know why my product has not yet...,Delivery,1
9ed2a6bc2282fd2b0105055631afa57f,"As of today, October 21, 2017, the order has n...",Delivery,1
2fc8295a24978092328d3a329d22940e,I received the following email and need to kno...,Customer Service,1
3450ec3bbabeb09a08b00fc72da87a30,Good afternoon. I haven't received all the pro...,Customer Service,1
efe49f1d6f951dd88b51e6ccd4cc548f,My product arrived and I already have to retur...,Customer Service,1

In [70]:
# check data types
reviews.dtypes

order_id                     str
review_score               int64
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
review_class                 str
dtype: object

In [71]:
reviews.isna().sum()

order_id                   0
review_score               0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
review_class               0
dtype: int64

In [72]:
pd.DataFrame.to_csv(reviews, 'olist_order_reviews_dataset.csv')

PermissionError: [Errno 13] Permission denied: 'olist_order_reviews_dataset.csv'

In [ ]:
reviews

,Unnamed: 0.1,Unnamed: 0,review_id,order_id,review_score,review_comment_message,review_creation_date,review_answer_timestamp,review_class
0,0,0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,No Comment,1/18/2018 0:00,1/18/2018 21:46,No Comment
1,1,1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,No Comment,3/10/2018 0:00,3/11/2018 3:05,No Comment
2,2,2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,No Comment,2/17/2018 0:00,2/18/2018 14:36,No Comment
3,3,3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,I received it well before the estimated date.,4/21/2017 0:00,4/21/2017 22:02,Delivery
4,4,4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,"Congratulations Lannister stores, I loved shop...",3/1/2018 0:00,3/2/2018 10:26,Customer Service
...,...,...,...,...,...,...,...,...,...
99219,99219,99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,No Comment,7/7/2018 0:00,7/14/2018 17:18,No Comment
99220,99220,99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,No Comment,12/9/2017 0:00,12/11/2017 20:06,No Comment
99221,99221,99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,"Excellent backpack, super fast delivery. I hig...",3/22/2018 0:00,3/23/2018 9:10,Customer Service
99222,99222,99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,No Comment,7/1/2018 0:00,7/2/2018 12:59,No Comment
99223,99223,99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,My product arrived and I already have to retur...,7/3/2017 0:00,7/3/2017 21:01,Customer Service

In [ ]:
reviews.groupby('review_class').count()

,Unnamed: 0.1,Unnamed: 0,review_id,order_id,review_score,review_comment_message,review_creation_date,review_answer_timestamp
review_class,,,,,,,,
Customer Service,7223,7223,7223,7223,7223,7223,7223,7223
Delivery,13134,13134,13134,13134,13134,13134,13134,13134
No Comment,58277,58277,58277,58277,58277,58277,58277,58277
Other,5556,5556,5556,5556,5556,5556,5556,5556
Packaging,2552,2552,2552,2552,2552,2552,2552,2552
Price,2582,2582,2582,2582,2582,2582,2582,2582
Product Quality,9900,9900,9900,9900,9900,9900,9900,9900

In [ ]:
reviews.shape

(99224, 9)

In [ ]:
reviews.drop_duplicates(inplace= True)

In [ ]:
pd.DataFrame.to_csv(reviews, 'olist_order_reviews_dataset.csv')