In [123]:
import pandas as pd

In [124]:
products = pd.read_csv('olist_products_dataset.csv')

In [125]:
products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [126]:
def category_translation(category_name):
    category = {
'beleza_saude': 'health_beauty',
'informatica_acessorios': 'computers_accessories',
'automotivo': 'auto',
'cama_mesa_banho': 'bed_bath_table',
'moveis_decoracao': 'furniture_decor',
'esporte_lazer': 'sports_leisure',
'perfumaria': 'perfumery',
'utilidades_domesticas': 'housewares',
'telefonia': 'telephony',
'relogios_presentes': 'watches_gifts',
'alimentos_bebidas': 'food_drink',
'bebes': 'baby',
'papelaria': 'stationery',
'tablets_impressao_imagem': 'tablets_printing_image',
'brinquedos': 'toys',
'telefonia_fixa': 'fixed_telephony',
'ferramentas_jardim': 'garden_tools',
'fashion_bolsas_e_acessorios': 'fashion_bags_accessories',
'eletroportateis': 'small_appliances',
'consoles_games': 'consoles_games',
'audio': 'audio',
'fashion_calcados': 'fashion_shoes',
'cool_stuff': 'cool_stuff',
'malas_acessorios': 'luggage_accessories',
'climatizacao': 'air_conditioning',
'construcao_ferramentas_construcao': 'construction_tools_construction',
'moveis_cozinha_area_de_servico_jantar_e_jardim': 'kitchen_dining_laundry_garden_furniture',
'construcao_ferramentas_jardim': 'construction_tools_garden',
'fashion_roupa_masculina': 'fashion_male_clothing',
'pet_shop': 'pet_shop',
'moveis_escritorio': 'office_furniture',
'market_place': 'market_place',
'eletronicos': 'electronics',
'eletrodomesticos': 'home_appliances',
'artigos_de_festas': 'party_supplies',
'casa_conforto': 'home_confort',
'construcao_ferramentas_ferramentas': 'construction_tools_tools',
'agro_industria_e_comercio': 'agro_industry_and_commerce',
'moveis_colchao_e_estofado': 'furniture_mattress_and_upholstery',
'livros_tecnicos': 'books_technical',
'casa_construcao': 'home_construction',
'instrumentos_musicais': 'musical_instruments',
'moveis_sala': 'furniture_living_room',
'construcao_ferramentas_iluminacao': 'construction_tools_lights',
'industria_comercio_e_negocios': 'industry_commerce_and_business',
'alimentos': 'food',
'artes': 'art',
'moveis_quarto': 'furniture_bedroom',
'livros_interesse_geral': 'books_general_interest',
'construcao_ferramentas_seguranca': 'construction_tools_safety',
'fashion_underwear_e_moda_praia': 'fashion_underwear_beach',
'fashion_esporte': 'fashion_sport',
'sinalizacao_e_seguranca': 'signaling_and_security',
'pcs': 'computers',
'artigos_de_natal': 'christmas_supplies',
'fashion_roupa_feminina': 'fashion_female_clothing',
'eletrodomesticos_2': 'home_appliances_2',
'livros_importados': 'books_imported',
'bebidas': 'drinks',
'cine_foto': 'cine_photo',
'la_cuisine': 'la_cuisine',
'musica': 'music',
'casa_conforto_2': 'home_comfort_2',
'portateis_casa_forno_e_cafe': 'small_appliances_home_oven_and_coffee',
'cds_dvds_musicais': 'cds_dvds_musicals',
'dvds_blu_ray': 'dvds_blu_ray',
'flores': 'flowers',
'artes_e_artesanato': 'arts_and_craftmanship',
'fraldas_higiene': 'diapers_and_hygiene',
'fashion_roupa_infanto_juvenil': 'fashion_childrens_clothes',
'seguros_e_servicos': 'security_and_services'
}
    if category_name in category:
        return category[category_name]
    return category_name

In [127]:
products['product_category_name'] = products['product_category_name'].apply(category_translation)

In [128]:
products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,art,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,sports_leisure,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,baby,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,housewares,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,furniture_decor,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construction_tools_lights,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,bed_bath_table,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,computers_accessories,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,bed_bath_table,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [129]:
# check nulls
products.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [130]:
products.shape

(32951, 9)

In [131]:
products.drop_duplicates(inplace=True , keep='first')

In [132]:
products['product_category_name'] = products['product_category_name'].fillna('uncategorized')

In [133]:
products.shape

(32951, 9)

In [134]:
products.dtypes

product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [135]:
COMMISSION_RATES = {
    'furniture_bedroom': 0.17,
    'sports_leisure': 0.15,
    'telephony': 0.18,
    'health_beauty': 0.18,
    'construction_tools_construction': 0.13,
    'fashion_childrens_clothes': 0.20,
    'cine_photo': 0.16,
    'office_furniture': 0.17,
    'fashion_sport': 0.19,
    'security_and_services': 0.15,
    'dvds_blu_ray': 0.12,
    'toys': 0.14,
    'food': 0.10,
    'home_appliances_2': 0.15,
    'arts_and_craftmanship': 0.18,
    'home_confort': 0.16,
    'fashion_male_clothing': 0.20,
    'party_supplies': 0.13,
    'computers_accessories': 0.15,
    'fashion_female_clothing': 0.20,
    'musical_instruments': 0.17,
    'art': 0.18,
    'construction_tools_safety': 0.13,
    'books_imported': 0.10,
    'construction_tools_lights': 0.13,
    'uncategorized': 0.15,
    'air_conditioning': 0.16,
    'stationery': 0.12,
    'pc_gamer': 0.17,
    'portateis_cozinha_e_preparadores_de_alimentos': 0.15,
    'audio': 0.16,
    'fixed_telephony': 0.15,
    'kitchen_dining_laundry_garden_furniture': 0.16,
    'pet_shop': 0.14,
    'cds_dvds_musicals': 0.12,
    'luggage_accessories': 0.17,
    'la_cuisine': 0.14,
    'computers': 0.17,
    'christmas_supplies': 0.13,
    'small_appliances_home_oven_and_coffee': 0.15,
    'consoles_games': 0.18,
    'industry_commerce_and_business': 0.14,
    'market_place': 0.15,
    'garden_tools': 0.12,
    'housewares': 0.12,
    'electronics': 0.18,
    'home_construction': 0.14,
    'food_drink': 0.10,
    'tablets_printing_image': 0.15,
    'fashion_shoes': 0.20,
    'fashion_bags_accessories': 0.20,
    'drinks': 0.10,
    'bed_bath_table': 0.14,
    'agro_industry_and_commerce': 0.13,
    'furniture_living_room': 0.17,
    'small_appliances': 0.15,
    'watches_gifts': 0.18,
    'home_comfort_2': 0.16,
    'cool_stuff': 0.15,
    'construction_tools_garden': 0.12,
    'perfumery': 0.20,
    'construction_tools_tools': 0.13,
    'signaling_and_security': 0.14,
    'fashion_underwear_beach': 0.20,
    'flowers': 0.15,
    'books_general_interest': 0.10,
    'diapers_and_hygiene': 0.12,
    'auto': 0.12,
    'music': 0.12,
    'baby': 0.12,
    'home_appliances': 0.15,
    'books_technical': 0.10,
    'furniture_decor': 0.17,
    'furniture_mattress_and_upholstery': 0.17,
}

In [136]:
COMMISSION_RATES.__len__()

74

In [137]:
products['commission_rate'] = products['product_category_name'].map(COMMISSION_RATES)

In [138]:
products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,commission_rate
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,40.0,287.0,1.0,225.0,16.0,10.0,14.0,0.20
1,3aa071139cb16b67ca9e5dea641aaa2f,art,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,0.18
2,96bd76ec8810374ed1b65e291975717f,sports_leisure,46.0,250.0,1.0,154.0,18.0,9.0,15.0,0.15
3,cef67bcfe19066a932b7673e239eb23d,baby,27.0,261.0,1.0,371.0,26.0,4.0,26.0,0.12
4,9dc1a7de274444849c219cff195d0b71,housewares,37.0,402.0,4.0,625.0,20.0,17.0,13.0,0.12
...,...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,furniture_decor,45.0,67.0,2.0,12300.0,40.0,40.0,40.0,0.17
32947,bf4538d88321d0fd4412a93c974510e6,construction_tools_lights,41.0,971.0,1.0,1700.0,16.0,19.0,16.0,0.13
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,bed_bath_table,50.0,799.0,1.0,1400.0,27.0,7.0,27.0,0.14
32949,83808703fc0706a22e264b9d75f04a2e,computers_accessories,60.0,156.0,2.0,700.0,31.0,13.0,20.0,0.15
32950,106392145fca363410d287a815be6de4,bed_bath_table,58.0,309.0,1.0,2083.0,12.0,2.0,7.0,0.14

In [139]:
pd.DataFrame.to_csv(products, 'C:\\Users\\Lenovo\\Desktop\\Analysis Projects\\Olist Store\\cleaned datasets\\olist_products_dataset.csv',index=False)