In [1]:
import pandas as pd

In [2]:
reviews = pd.read_csv('olist_order_reviews_dataset.csv',index_col=0)

In [3]:
reviews

,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,review_class
review_id,,,,,,,
7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,No Comment,2018-01-18 00:00:00,2018-01-18 21:46:59,No Comment
80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,No Comment,2018-03-10 00:00:00,2018-03-11 03:05:13,No Comment
228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,No Comment,2018-02-17 00:00:00,2018-02-18 14:36:24,No Comment
e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06,Other
f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53,Customer Service
...,...,...,...,...,...,...,...
574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,No Comment,2018-07-07 00:00:00,2018-07-14 17:18:30,No Comment
f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,No Comment,2017-12-09 00:00:00,2017-12-11 20:06:42,No Comment
b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43,Other
1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,No Comment,2018-07-01 00:00:00,2018-07-02 12:59:13,No Comment
efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49,Other

In [4]:
# check duplicates
reviews.duplicated().sum()

np.int64(0)

In [5]:
# check nulls
reviews.isna().sum()

order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message         0
review_creation_date           0
review_answer_timestamp        0
review_class                   0
dtype: int64

In [6]:
reviews.shape

(99224, 7)

In [7]:
reviews['review_comment_message'] = reviews['review_comment_message'].fillna('No Comment')

In [8]:
reviews

,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,review_class
review_id,,,,,,,
7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,No Comment,2018-01-18 00:00:00,2018-01-18 21:46:59,No Comment
80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,No Comment,2018-03-10 00:00:00,2018-03-11 03:05:13,No Comment
228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,No Comment,2018-02-17 00:00:00,2018-02-18 14:36:24,No Comment
e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06,Other
f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53,Customer Service
...,...,...,...,...,...,...,...
574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,No Comment,2018-07-07 00:00:00,2018-07-14 17:18:30,No Comment
f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,No Comment,2017-12-09 00:00:00,2017-12-11 20:06:42,No Comment
b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43,Other
1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,No Comment,2018-07-01 00:00:00,2018-07-02 12:59:13,No Comment
efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49,Other

In [9]:
def classify_review(text):
    if not isinstance(text, str) or text.strip().lower() == "no comment" or text.strip() == "":
        return "No Comment"

    text = text.lower()

    if any(word in text for word in [
        "box", "bag", "inside", "packaging", "sealed", "wrapped",
        "bubble", "wrap", "seal", "crushed", "packaged", "came",
        "bubble wrap", "without packaging", "broken box", "crushed box"
    ]):
        return "Packaging"

    elif any(word in text for word in [
        "money", "price", "worth", "value", "cost", "expensive",
        "paid", "buying", "overpriced", "cheap", "affordable",
        "waste of money", "not worth", "good price", "great value"
    ]):
        return "Price"

    elif any(word in text for word in [
        "service", "response", "exchange", "refund", "seller",
        "return", "contact", "waiting", "sent", "lannister",
        "customer", "store", "shop", "support", "ignored",
        "no reply", "no response", "unresolved", "resolved"
    ]):
        return "Customer Service"

    elif any(word in text for word in [
        "arrived", "delivery", "schedule", "ahead", "deadline",
        "delivered", "shipping", "date", "days", "dispatch",
        "fast delivery", "quick delivery", "late", "delayed",
        "not delivered", "still waiting", "never received",
        "tracking", "transit", "courier", "on time", "early"
    ]):
        return "Delivery"

    elif any(word in text for word in [
        "quality", "excellent", "good", "great", "loved",
        "beautiful", "expected", "liked", "perfect", "product",
        "works", "durable", "defective", "broken", "damaged",
        "fake", "original", "inferior", "poor quality", "well made",
        "not as described", "exactly as described", "sturdy", "flimsy"
    ]):
        return "Product Quality"

    return "Other"

In [10]:
reviews['review_class'] = reviews['review_comment_message'].apply(classify_review)
reviews['review_class']

review_id
7bc2406110b926393aa56f80a40eba40          No Comment
80e641a11e56f04c1ad469d5645fdfde          No Comment
228ce5500dc1d8e020d8d1322874b6f0          No Comment
e64fb393e7b32834bb789ff8bb30750e               Other
f7c4243c7fe1938f181bec41a392bdeb    Customer Service
                                          ...
574ed12dd733e5fa530cfd4bbf39d7c9          No Comment
f3897127253a9592a73be9bdfdf4ed7a          No Comment
b3de70c89b1510c4cd3d0649fd302472               Other
1adeb9d84d72fe4e337617733eb85149          No Comment
efe49f1d6f951dd88b51e6ccd4cc548f               Other
Name: review_class, Length: 99224, dtype: str

In [11]:
# check comments of bad score reviews
reviews[['review_comment_message','review_class', 'review_score']][(reviews['review_score'] == 1) & (reviews['review_comment_message'] != 'No Comment')]

,review_comment_message,review_class,review_score
review_id,,,
373cbeecea8286a2b66c97b1b157ec46,Péssimo,Other,1
2c5e27fc178bde7ac173c9c62c31b070,Não gostei ! Comprei gato por lebre,Other,1
58044bca115705a48fe0e00a21390c54,Sempre compro pela Internet e a entrega ocorre...,Other,1
9fd59cd04b42f600df9f25e54082a8d1,Nada de chegar o meu pedido.,Other,1
e233e51d11511bf30e568c76360ace52,recebi somente 1 controle Midea Split ESTILO.\...,Other,1
...,...,...,...
9bab7509047d0b236205e330172b384d,Gostaria de saber porque meu produto ainda não...,Other,1
9ed2a6bc2282fd2b0105055631afa57f,Ate hoje dia 21/10/2017 o pedido não foi entre...,Other,1
2fc8295a24978092328d3a329d22940e,Eu recebi o seguinte email e preciso saber com...,Customer Service,1
3450ec3bbabeb09a08b00fc72da87a30,Boa tarde. \r\nNão recebo todos os produtos fa...,Other,1
efe49f1d6f951dd88b51e6ccd4cc548f,"meu produto chegou e ja tenho que devolver, po...",Other,1

In [12]:
# check data types
reviews.dtypes

order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
review_class                 str
dtype: object

In [13]:
reviews.isna().sum()

order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message         0
review_creation_date           0
review_answer_timestamp        0
review_class                   0
dtype: int64

In [14]:
pd.DataFrame.to_csv(reviews, 'olist_order_reviews_dataset.csv')

In [15]:
reviews

,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,review_class
review_id,,,,,,,
7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,No Comment,2018-01-18 00:00:00,2018-01-18 21:46:59,No Comment
80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,No Comment,2018-03-10 00:00:00,2018-03-11 03:05:13,No Comment
228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,No Comment,2018-02-17 00:00:00,2018-02-18 14:36:24,No Comment
e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06,Other
f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53,Customer Service
...,...,...,...,...,...,...,...
574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,No Comment,2018-07-07 00:00:00,2018-07-14 17:18:30,No Comment
f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,No Comment,2017-12-09 00:00:00,2017-12-11 20:06:42,No Comment
b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43,Other
1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,No Comment,2018-07-01 00:00:00,2018-07-02 12:59:13,No Comment
efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49,Other

In [16]:
reviews.groupby('review_class').count()

,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
review_class,,,,,,
Customer Service,1758,1758,458,1758,1758,1758
Delivery,58,58,10,58,58,58
No Comment,58274,58274,1738,58274,58274,58274
Other,38443,38443,9162,38443,38443,38443
Packaging,102,102,25,102,102,102
Price,138,138,41,138,138,138
Product Quality,451,451,134,451,451,451

In [17]:
reviews.shape

(99224, 7)

In [18]:
reviews.drop_duplicates(inplace= True)

In [19]:
pd.DataFrame.to_csv(reviews,'order_reviews.csv')